const URL_MASTERLOGIC_API =
  "https://raw.githubusercontent.com/StevenGV20/fakeapi-testing/main";
const GRUPOS_COLS_MODAL_DESKTOP = [
  "GRUPO",
  "SEDE",
  "VOLUMEN TOTAL",
  "MONTO TOTAL",
];
const GRUPOS_COLS_MODAL_MOBILE = ["GRUPO", ""];

const GRUPOS_COLS_DESKTOP = [
  "GRUPO",
  "SEDE",
  "VOLUMEN (m3)",
  "MONTO TOTAL",
  "UBIGEO",
  "VEHÍCULO",
  "RUTA",
  "MONTO",
  "",
];

const GRUPOS_COLS_MOBILE = ["GRUPO", " ", "VEHÍCULO", ""];
const VEHICULOS_DISPONIBILIDAD_COLS_DESKTOP = [
  "VEHÍCULO",
  "CHOFER",
  "SEDE",
  "VOLUMEN MAXIMO (m3)",
  "VOLUMEN ACTUAL ASIGNADO (m3)",
  "VOLUMEN DISPONIBLE (m3)",
  "",
];

const VEHICULOS_DISPONIBILIDAD_COLS_MOBILE = ["VEHÍCULO", ""];

const MANTENIMIENTO_VEHICULOS_TABLE_COLS_DESKTOP = [
  "CODIGO",
  "PLACA",
  "CHOFER",
  "N° DE LICENCIA",
  "ESTADO",
  "PROPIETARIO",
  "SEDE",
  "VOLUMEN MAXIMO",
  "TARA",
  "",
];
const MANTENIMIENTO_RUTAS_TABLE_COLS_DESKTOP = [
  "CODIGO",
  "SEDE",
  "DESCRIPCION",
  "VOLUMEN MINIMO",
  "VOLUMEN MAXIMO",
  "MONTO",
  "",
];
const MANTENIMIENTO_RUTAS_DISTRITOS_TABLE_COLS_DESKTOP = [
  "RUTA",
  "DISTRITO",
  "",
];
const MANTENIMIENTO_DISTANCIAS_TABLE_COLS_DESKTOP = [
  "SEDE",
  "DISTRITO",
  "KM",
  "",
];

export {
  URL_MASTERLOGIC_API,
  GRUPOS_COLS_MODAL_DESKTOP,
  GRUPOS_COLS_MODAL_MOBILE,
  GRUPOS_COLS_DESKTOP,
  GRUPOS_COLS_MOBILE,
  VEHICULOS_DISPONIBILIDAD_COLS_DESKTOP,
  VEHICULOS_DISPONIBILIDAD_COLS_MOBILE,
  MANTENIMIENTO_VEHICULOS_TABLE_COLS_DESKTOP,
  MANTENIMIENTO_RUTAS_TABLE_COLS_DESKTOP,
  MANTENIMIENTO_RUTAS_DISTRITOS_TABLE_COLS_DESKTOP,
  MANTENIMIENTO_DISTANCIAS_TABLE_COLS_DESKTOP,
};
