const PAGE_GENERAR_GRR = "GENERAR GUIA DE REMISIÓN DE REMITENTE";
const PAGE_AGRUPAR_OD = "AGRUPAR ORDEN DE DESPACHO";
const PAGE_ASIGNAR_VEHICULO = "ASIGNAR VEHICULO";
const PAGE_GENERAR_OT_Y_GRT =
  "GENERAR ORDEN DE TRABAJO Y GUIA DE REMISION DE TRANSPORTISTA";

export {
  PAGE_GENERAR_GRR,
  PAGE_AGRUPAR_OD,
  PAGE_ASIGNAR_VEHICULO,
  PAGE_GENERAR_OT_Y_GRT,
};
