const PAGE_GENERAR_GRR = "GENERAR GUIA DE REMISIÓN DE REMITENTE";
const PAGE_AGRUPAR_OD = "AGRUPAR ORDEN DE DESPACHO";
const PAGE_ASIGNAR_VEHICULO = "ASIGNAR VEHICULO";
const PAGE_GENERAR_OT_Y_GRT =
  "GENERAR ORDEN DE TRABAJO Y GUIA DE REMISION DE TRANSPORTISTA";
const PAGE_MANTENIMIENTO_VEHICULOS = "MANTENIMIENTO VEHÍCULOS";
const PAGE_MANTENIMIENTO_RUTAS = "MANTENIMIENTO RUTAS";
const PAGE_MANTENIMIENTO_DISTRITOS_RUTAS = "MANTENIMIENTO DISTRITOS_RUTAS";
const PAGE_MANTENIMIENTO_DISTANCIAS = "MANTENIMIENTO DISTANCIAS";

export {
  PAGE_GENERAR_GRR,
  PAGE_AGRUPAR_OD,
  PAGE_ASIGNAR_VEHICULO,
  PAGE_GENERAR_OT_Y_GRT,
  PAGE_MANTENIMIENTO_VEHICULOS,
  PAGE_MANTENIMIENTO_RUTAS,
  PAGE_MANTENIMIENTO_DISTRITOS_RUTAS,
  PAGE_MANTENIMIENTO_DISTANCIAS,
};
